#!/bin/python3
print('''
_________________________________________________________
|							|
|  Please cite as:					|
|  Emanuel Contreras-Cuevas, Humberto Estrada-Lara,     |
|  Joaquín Barroso-Flores. "UVeh-Vis: a python tool   	|
|  for plotting UV-Vis spectra from excited states      |
|  calculations" (2023) Git Hub                         |
|  https://github.com/joaquinbarroso/UVeh-Vis           |
|                                                       |
—————————————————————————————————————————————————————————
	''')
time.sleep(1)
print('''
If you have any issue (or recommendation), you can upload it to the repository issues:
https://github.com/joaquinbarroso/UVeh-Vis/issues
	''')
