#!/bin/usr/python3
import numpy as np
import pandas as pd
head=['Wavelenght']
array='A=np.array([wavelenght,'
for f in range (1,a):
	ABS_n='ABS_'+str(f)
	array+=ABS_n
	if f<a-1:
		array+=','
	else:
		array+='])'
	head.append(datas[f-1].split(".")[0])
exec(array)
MAT=np.transpose(A)
my_df=pd.DataFrame(MAT)
my_df.to_csv('output.csv', index=False, header=head)

